---
name: ros_buildfarm release reconfigure
description: Run a ROS buildfarm reconfigure job for release jobs
inputs:
  config_url:
    description: URL of the buildfarm configuration index
    required: true
    default: https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/production/index.yaml
  config_name:
    description: Name of the release configuration
    required: true
    default: default
  ros_distro:
    description: ROS distribution name
    required: true
  pkg_names:
    description: Names of the package to reconfigure jobs for
    required: false

runs:
  using: composite
  steps:
    - id: ros_buildfarm_job
      env:
        PODMAN_USERNS: keep-id
      shell: bash
      run: |
        echo ::group::Generate job
        package_names_arg=""
        if [[ "${{inputs.pkg_names}}" != "" ]]; then
          package_names_arg="--package-names ${{inputs.pkg_names}}"
        fi

        pushd $(mktemp -d)
        mkdir -p docker_dir
        curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc -o ros.asc
        run_release_reconfigure_job.py \
          ${{inputs.config_url}} ${{inputs.ros_distro}} ${{inputs.config_name}} \
          --distribution-repository-urls http://repo.ros2.org/ubuntu/testing http://repositories.ros.org/ubuntu/testing \
          --distribution-repository-key-files $PWD/ros.asc $PWD/ros.asc \
          --dockerfile-dir $PWD/docker_dir \
          --groovy-script /tmp/reconfigure_jobs.groovy \
          ${package_names_arg}
        echo ::endgroup::

        echo ::group::Build container
        docker build --force-rm -t release_reconfigure_jobs $PWD/docker_dir
        echo ::endgroup::

        echo ::group::Run job
        docker run --rm \
          -v ${{github.workspace}}:/tmp/ros_buildfarm:ro \
          release_reconfigure_jobs
        echo ::endgroup
