    <jenkins.triggers.ReverseBuildTrigger>
      <spec/>
      <upstreamProjects>@(','.join(sorted(upstream_projects)))</upstreamProjects>
      <threshold>
        <name>UNSTABLE</name>
        <ordinal>1</ordinal>
        <color>YELLOW</color>
        <completeBuild>true</completeBuild>
      </threshold>
    </jenkins.triggers.ReverseBuildTrigger>
